#############################################################
# This ServiceNow-created file contains the path to the app in this repo
# path=<path to app content in your repo>
# For example, if the app content resides in a folder named x_my_custom_app, the path value would be:
# path=/x_my_custom_app
# Update the path value when you move the app to a new repo location.
############################################################
#
#Sun Aug 31 23:58:54 PDT 2025
path=4c2b85dceb3f6610e4a8f1b4cad0cd2f
